### ISSUE TITLE
error after updating to storybook 8

### ISSUE THREAD

**Issue by pkyeck** [linearlabs-workspace/storybook-addon-mock#211]
Hi,
I'm trying to update my storybook v7 installation to v8:
- ran the storybook migration
- updated the plugin to v5.0.0

but I'm seeing `fn is not a function` with the `withRoundTrip.js:74:1` mentioned in the stack-trace

```
TypeError: fn is not a function
    at hookified (runtime.js:95:10605)
    at runtime.js:111:3256
    at runtime.js:111:3717
    at withRoundTrip (withRoundTrip.js:74:1)
    at hookified (runtime.js:95:10605)
    at runtime.js:111:3256
    at runtime.js:111:3717
    at i (preview.cjs:5:1)
    at hookified (runtime.js:95:10605)
    at runtime.js:111:3256
```

anyone else getting these errors after the update?

**Comment by emersonthis** [comment]
I'm seeing a very similar error and I'm still on Storybook v7.
